### PR TITLE
Stop GRAPH statements at edge of SERVICE

### PR DESCRIPTION
**Pull request by joachimvh**
Quick fix for https://github.com/comunica/comunica/issues/1294

Not immediately merging until we know the answer to some questions:

Question is though, is this necessary? Are these queries not equivalent? Would have to go look in the spec and see.

Other question is if there are other statements that potentially have a similar issue.

### CODE REVIEW

**Comment by rubensworks** [comment]
That fix came quickly 😅 

> Are these queries not equivalent?

If you refer to the query in https://github.com/comunica/comunica/issues/1294, then no, they are certainly not equivalent.

> Other question is if there are other statements that potentially have a similar issue.

Maybe also the combination of property paths with graphs?

**Comment by joachimvh** [comment]
> Maybe also the combination of property paths with graphs?

Property paths are handled identically as normal triples in a BGP, so all solutions will apply to both.

The problem is that there is no way of knowing what the original query was if it was converted to quads. E.g., the following two queries:
```sparql
SELECT * WHERE {
  GRAPH <myGraph> {
    ?s ?p ?o.
    FILTER(...)
  }
}
```
```sparql
SELECT * WHERE {
  GRAPH <myGraph> {
    ?s ?p ?o.
  }
  FILTER(...)
}
```

These will result in identical algebra when using quads. So when converting back some heuristics have to be used. Currently the library tries to maximize the operations it includes in the GRAPH block, which is why the SERVICE block got included when converting back. So it is possible that there are other operations where there could be similar unwanted formatting changes. Could be that SERVICE is the only one but would have to go through all of the possible operations to check.

**Comment by joachimvh** [comment]
Had a look and didn't immediately see any other keywords that might cause issues so just doing this one might be fine. The bigger issue is actually this comment:

> If you refer to the query in [comunica/comunica#1294](https://github.com/comunica/comunica/issues/1294), then no, they are certainly not equivalent.

If this is true, there is a different issue that needs to be resolved. Because both of those queries (`SERVICE ... { GRAPH ... }` and `GRAPH ... { SERVICE ... }` will currently produce the same algebra, being the following one:

```json
{
  "type": "project",
  "input": {
    "type": "service",
    "input": {
      "type": "bgp",
      "patterns": [
        {
          "type": "pattern",
          "termType": "Quad",
          "subject": { "termType": "Variable", "value": "s" },
          "predicate": { "termType": "Variable", "value": "p" },
          "object": {
            "termType": "Literal",
            "value": "foo",
            "datatype": { "termType": "NamedNode", "value": "http://www.w3.org/2001/XMLSchema#string" }
          },
          "graph": { "termType": "NamedNode", "value": "http://iam.ucdavis.edu" }
        }
      ]
    },
    "name": { "termType": "NamedNode", "value": "http://localhost:3030/experts/sparql" },
    "silent": false
  },
  "variables": [
    { "termType": "Variable", "value": "p" },
    { "termType": "Variable", "value": "s" }
  ]
}
```

So this fix would just shift the problem. My suggestion would be to instead not modify the triples in a SERVICE block if there is a GRAPH block around it. So in the case of `GRAPH ... { SERVICE ... }` the above algebra would instead be the same one, but with the default graph in the BGP instead. This would cause all information of the `GRAPH` statement to be lost, so this would result in the following SPARQL when converting back:

```sparql
SELECT ?p ?s WHERE {
  SERVICE <http://localhost:3030/experts/sparql> { ?s ?p "foo". } }
```

But I think this is actually fine as SERVICE is defined to ignore the information of the active dataset. Looking at the algebra definitions we have the following:
* [GRAPH](https://www.w3.org/TR/sparql11-query/#defn_evalGraph): `eval(D(G), Graph(IRI, P)) = eval(D(D[IRI]), P)`
* [SERVICE](https://www.w3.org/TR/sparql11-federated-query/#algebra_service): `eval(D(G), Service(IRI, P, SilentOp)) = Invocation( IRI, P, SilentOp )`

So algebra of `GRAPH ... { SERVICE ... }` would be
```
eval(D(G), Graph(IRI1,eval(D(G), Service(IRI2, P, SilentOp))))
  = eval(D(D[IRI1]), eval(D(G), Service(IRI2, P, SilentOp)))
  = Invocation( IRI2, P, SilentOp )
```
which is the same result as just applying SERVICE on IRI2.

**Comment by joachimvh** [comment]
Will release as v4.3.2

**Pull request merged**
